Update Docker and Docker Compose.
nuveo/boxos pull request #5
Opened 2018-03-21 23:32 UTC by perylemke

Hello,

Updating Docker and Docker Compose in BoxOS.

Regards,

2018-03-21 23:37 UTC, avelino requested changes

2018-03-21 23:37 UTC, avelino commented on initial.sh
> +#gpg_fingerprint="58118E89F3A912897C070ADBF76221572C52609D"
remove comment

2018-03-21 23:43 UTC, perylemke commented
Comment removed. Thanks :)

2018-03-21 23:44 UTC, avelino approved these changes
LGTM

2018-03-22 10:10 UTC, crgimenes approved these changes
LGTM

2018-03-22 10:24 UTC, merged